# Generated by Django 3.1.2 on 2020-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('savings', models.IntegerField()),
                ('about', models.CharField(max_length=250)),
            ],
        ),
    ]
